- name: Set up NodeSource
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

- name: Install Node.js package
  apt: pkg=nodejs update_cache=yes
  
- name: Update all packages to the latest version
  apt: upgrade=dist

- name: Install Grunt via npm
  npm: name=grunt-cli global=yes

- name: Install Gulp via npm
  npm: name=gulp global=yes


